language: scala

scala:
  - 2.13.0

env:
  - SCALAJS_VERSION=         ADOPTOPENJDK=8
  - SCALAJS_VERSION=0.6.29   ADOPTOPENJDK=8
  - SCALAJS_VERSION=1.0.0-M8 ADOPTOPENJDK=8
  - SCALAJS_VERSION=         ADOPTOPENJDK=11

before_install:
  # adding $HOME/.sdkman to cache would create an empty directory, which interferes with the initial installation
  - "[[ -d $HOME/.sdkman/bin ]] || rm -rf $HOME/.sdkman/"
  - curl -sL https://get.sdkman.io | bash
  - echo sdkman_auto_answer=true > $HOME/.sdkman/etc/config
  - source "$HOME/.sdkman/bin/sdkman-init.sh"

install:
  - sdk install java $(sdk list java | grep -o "$ADOPTOPENJDK\.[0-9\.]*hs-adpt" | head -1)
  - unset JAVA_HOME
  - java -Xmx32m -version
  - git fetch --tags # get all tags for sbt-dynver

script: ./build.sh

before_cache:
  - rm -f $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache     -name "ivydata-*.properties" | xargs rm
  - find $HOME/.sbt            -name "*.lock"               | xargs rm
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.cache/coursier
    - $HOME/.sdkman
